[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
serde={version="1.0.160", features=["derive"]}
serde_json = "1.0.96"
spin-sdk = { git = "https://github.com/fermyon/spin", tag = "v0.7.0" }
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "cb871cfa1ee460b51eb1d144b175b9aab9c50aba" }